# Generated by Django 2.2 on 2020-06-10 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('presenter_id', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='presenters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('presentation_id', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('timeslot', models.CharField(default=' ', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_slots', models.DecimalField(decimal_places=0, default=50, max_digits=10)),
                ('number_of_slots_remaining', models.DecimalField(decimal_places=0, default=50, max_digits=10)),
                ('location', models.CharField(default=' ', max_length=50)),
                ('description', models.CharField(default=' ', max_length=200)),
                ('presenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='Agile_Con.Presenter')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('attendee_id', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
